#!/bin/bash -l
#PBS -l nodes=1:ppn=24,mem=60gb,walltime=3:00:00
#PBS -m abe
#PBS -M bzang@umn.edu

cd /home/fahrenkr/zangx020/genome_ossabaw/trimmed

STAR --genomeDir  ~/genome_ossabaw/trimmed/starindex --genomeLoad LoadAndKeep --readFilesIn 1513_NoIndex_L007_R1_001_val_1.fq 1513_NoIndex_L007_R2_001_val_2.fq --outFileNamePrefix 007 --runThreadN 24
STAR --genomeDir  ~/genome_ossabaw/trimmed/starindex --genomeLoad LoadAndKeep --readFilesIn 1513_NoIndex_L008_R1_001_val_1.fq 1513_NoIndex_L008_R2_001_val_2.fq --outFileNamePrefix 008 --runThreadN 24
